name: Build and deploy

# Can be triggered by push and by manual interaction
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Perform build
        run: pnpm build
    
      - name: Create artifact
        uses: actions/upload-artifact@v4 
        with:
          name: test-artifact
          path: dist/www
          
    # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with: 
          name: test-artifact
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4        
    

      # TODO:
      # - Build the application (pnpm build)
      # - Create an artifact (archive) that contains the dist/www directoy using actions/upload-artifact@v4
      # - In a separate job, deploy the content of that archive to GitHub Pages
